# hyperparam.yaml
# By default uses bayesian hyperparameter optimization
trainingInput:
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 30
    maxParallelTrials: 5
    hyperparameterMetricTag: mean_squared_error
    enableTrialEarlyStopping: TRUE 
    params:
    - parameterName: n_estimators
      type: INTEGER
      minValue: 100
      maxValue: 1400
      scaleType: UNIT_LINEAR_SCALE