#!/bin/bash

# Customizable environmental variables
BUCKET_NAME=$1 #"zd-ai-platform-performanceattribution-training-bucket"
SCALE_TIER=${2:-"STANDARD_1"} #STANDARD_1

# Fixed environment variables (DO NOT CHANGE)
JOB_NAME="rf_training$(date +"%Y%m%d_%H%M%S")"
JOB_DIR=gs://$BUCKET_NAME/job_dir
TRAINING_PACKAGE_PATH="./trainer_module/"
MAIN_TRAINER_MODULE="trainer_module.train"
REGION="europe-west1"
RUNTIME_VERSION=1.13
PYTHON_VERSION=3.5
HPTUNING_CONFIG="hp_config.yaml"

# Send training job to the cloud
gcloud ai-platform jobs submit training $JOB_NAME \
  --job-dir $JOB_DIR \
  --package-path $TRAINING_PACKAGE_PATH \
  --module-name $MAIN_TRAINER_MODULE \
  --region $REGION \
  --runtime-version=$RUNTIME_VERSION \
  --python-version=$PYTHON_VERSION \
  --scale-tier $SCALE_TIER \
  --config $HPTUNING_CONFIG